apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-flag-platform
  namespace: feature-flag-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: feature-flag-platform
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: feature-flag-platform
    spec:
      containers:
        - name: app
          image: feature-flag-platform:REPLACE_ME
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: FEATURE_FLAGS_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: feature-flag-platform-config
                  key: FEATURE_FLAGS_DB_URL
            - name: FEATURE_FLAGS_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: feature-flag-platform-secret
                  key: FEATURE_FLAGS_DB_USERNAME
            - name: FEATURE_FLAGS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: feature-flag-platform-secret
                  key: FEATURE_FLAGS_DB_PASSWORD
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            failureThreshold: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 128Mi
