create table audit_events (
    id bigint generated by default as identity primary key,
    flag_key text not null,
    event_type text not null check (
        event_type in (
            'FLAG_CREATED',
            'FLAG_ENABLED',
            'FLAG_DISABLED',
            'ROLLOUT_PERCENTAGE_CHANGED',
            'TENANT_ALLOWLIST_CHANGED',
            'KILL_SWITCH_ENABLED',
            'KILL_SWITCH_DISABLED'
        )
    ),
    details jsonb not null,
    occurred_at timestamptz not null
);

create index audit_events_flag_key_idx on audit_events(flag_key);
create index audit_events_occurred_at_idx on audit_events(occurred_at);
