apiVersion: v1
kind: Service
metadata:
  name: feature-flag-postgres
  namespace: feature-flag-platform
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    app.kubernetes.io/name: feature-flag-postgres
